services:
  leveldb-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - leveldb-data:/app/data
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  leveldb-data: