services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb-demo
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password123
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - couchdb_network

  app:
    build: .
    container_name: couchdb-app
    ports:
      - "3000:3000"
    environment:
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password123
    depends_on:
      - couchdb
    networks:
      - couchdb_network

volumes:
  couchdb_data:

networks:
  couchdb_network:
    driver: bridge